name: todolist
description: A new Flutter application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI packages
  cupertino_icons: ^0.1.3
  flutter_slidable: ^0.5.7
  # UX
  toast:
  # local database
  moor_flutter: ^3.1.0
  # state management
  mobx: ^1.0.0
  flutter_mobx: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.0
  moor_generator: ^3.1.0
  mobx_codegen: ^1.0.0 

flutter:
  uses-material-design: true
